### PR TITLE
Reorganize packages

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Comment by Kubuxu** [comment]
I'm not in love with the `module` package name as it results in the imported package being called only module and the struct `module.Module` which can be confusing (no reference to f3),

**Comment by Stebalien** [comment]
Sub-packages are nice, but why `gpbft` and why not move some of that logic to the top level?

**Comment by ranchalp** [comment]
I have been thinking for a while that gpbft should be a separated package from the one that uses gpbft and carries the multi-instance consensus logic (participant). The "top" logic (although I woul rather them be separate and not just a sub-package of each other) should be the latter.

**Comment by Kubuxu** [comment]
I don't remember why exactly `gpbft`but IIRC, it is an acronym that explains the consensus.

**Comment by ranchalp** [comment]
> I don't remember why exactly gpbft but IIRC, it is an acronym that explains the consensus.

Technically we should at some point change the name everywhere from Granite to GossiPBFT, and that's where gpbft comes from.

**Comment by Kubuxu** [comment]
> Why not move some of that logic to the top level?
Should we move the module package to the top level?

**Review by ranchalp — APPROVED** [review]

**Review by anorth — APPROVED** [review]

**Comment by Kubuxu** [comment]
I don't love the fact that f3.Module exposes gpbft interfaces but we can clean this up in followup if we want to.
Ready for review.

**Pull request merged**
