### PR TITLE
Run cbor gen in parallel

### PR DESCRIPTION
**Pull request by masih**
Run cbor gen in parallel for faster generation.

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]

**Comment by Kubuxu** [comment]
I'm not sure this is safe as these packages have cross-dependencies on each other, and cbor-gen will use go toolkit to resolve symbols, but if it works, it works.

**Comment by Stebalien** [comment]
It's fine because we've already compiled so reflection uses the pre-compiled code.

**Comment by Kubuxu** [comment]
Ahh, right.

**Comment by Stebalien** [comment]
(I had the same "how does this even work" reaction)

**Pull request merged**
