### PR TITLE
Investigate flaky tests on CI

### PR DESCRIPTION
**Pull request by masih**
Set up a temporary workflow to run all flaky tests repeatedly on CI for further investigation.

### CODE REVIEW

**Comment by Stebalien** [comment]
Well, this looks like it helped a bit.

**Comment by Stebalien** [comment]
Hm. Well, I'm going to try increasing the timeout.

**Comment by masih** [comment]
@Stebalien Tests seem to only fail when run in conjunction with other tests. To me so far this seems like some kind of congestion issue deep in libp2p/pubsub stack.

**Comment by Stebalien** [comment]
> Tests seem to only fail when run in conjunction with other tests. To me so far this seems like some kind of congestion issue deep in libp2p/pubsub stack.

Or just a timing issue? We're using a mock network, so at least it's not some kind of port issue.

But yeah, it sounds like the solution is to simply not run them in parallel.

**Comment by masih** [comment]
Findings:
* Repeated individual tests do not fail (repeated up to 100 times each).
* They do fail when run in conjunction with other tests.
  * More specifically in conjunction with other tests in `f3_test.go`
* These tests are time-based, and use an artificial clock. Having reviewed the artificial clock code nothing immediately stands out.
* The cause of failure is waiting for a condition (e.g. instance number) that is never satisfied regardless of how long we wait (tested up to 30m timeout).
* Tests pass consistently after removing `t.Parallel()` (Repeated 50 times).

**Pull request closed without merging**
