### PR TITLE
Multi instance consensus

### PR DESCRIPTION
**Pull request by ranchalp**
Draft PR for multi-instance consensus, see #27 .

### CODE REVIEW

**Comment by ranchalp** [comment]
My opinion as reflected in the latest commit:

- F3 pushes newly finalized chains to Lotus, prompting perhaps a change of chain head on EC (by updated fork choice rule)
- Lotus pushes a call to receiveCanonicalChain every time EC changes its chain head (of the heaviest chain)⁠⁠
   - This means a new push from Lotus every time F3 pushes itself its finalised chain (this is important to trigger a new F3 instance).
- ⁠⁠Lotus also pushes all beacons and their associated epochs from drand to F3. F3 handles storing them and deleting them as needed by F3.

- ReceiveECChain is only called locally by f3 (Lotus only calls ReceiveCanonicalChain everytime its chain head changes)

**Comment by ranchalp** [comment]
The changes from the sync discussion and slack are both implemented here in the latest commit.

**Comment by ranchalp** [comment]
I think it would be easier to have `receiveBeacon` as a separated function (even if it makes sense to have the `beacons` in the `receiveCanonicalChain` method. This is because of #69 .

**Comment by anorth** [comment]
A lot has changed since this draft. I've had a quick look but not sure how much makes sense to attempt to rebase, vs just start over.
- Beacons are no longer relevant for timing
- Alarms don't need to identify instance
- I think some assumptions about chains received aren't quite right

I will try to recover our discussion about design here and jot some notes on the issue.

**Comment by ranchalp** [comment]
>     Beacons are no longer relevant for timing
But we still need beacons for the VRF.
>     Alarms don't need to identify instance
Not sure how the signaling works in the rebased code otherwise but for now I will trust you on that one.
>     I think some assumptions about chains received aren't quite right
Happy to discuss this once more detailed.

**Pull request closed without merging**
