### PR TITLE
Test sway at commit and converge for unseen candidates

### PR DESCRIPTION
**Pull request by masih**
Test that a participant sways for unseen candidates at `COMMIT` and `CONVERGE`.

Part of #237

### CODE REVIEW

**Comment by Kubuxu** [comment]
The codecov claims that CONVERGE sway is not hit.

**Comment by masih** [comment]
OK this is ready for another look; please let me know if you can think of a simpler way to test sway at CONVERGE. thanks

**Comment by Kubuxu** [comment]
What is the source of non-determinism? I think it should be only the chain seed, which leads to beacons.

**Comment by masih** [comment]
> What is the source of non-determinism?

Order of [chainsupport map](https://github.com/filecoin-project/go-f3/blob/33b0a89cde74412f58bc0bf7103438e8620d883c/gpbft/gpbft.go#L690) for committed state, and consequently candidate inclusion in `tryConverge` which determines whether we sway at CONVERGE or not.

**Comment by Kubuxu** [comment]
> Order of [chainsupport map](https://github.com/filecoin-project/go-f3/blob/33b0a89cde74412f58bc0bf7103438e8620d883c/gpbft/gpbft.go#L690) for committed state

That seems counter to the comment there, as the comment states that there should be only one.

**Comment by masih** [comment]
> That seems counter to the comment there, as the comment states that there should be only one.

Right. If i have not missed anything I think that would only hold if [this](https://github.com/filecoin-project/go-f3/issues/616) is fixed.

**Review by Stebalien — APPROVED** [review]

**Pull request merged**
