### PR TITLE
Use self-hosted runners for fuzzing

### PR DESCRIPTION
**Pull request by masih**
Testing IPDX self-hosted runners for fuzz tests.

### CODE REVIEW

**Comment by Stebalien** [comment]
Also see https://github.com/filecoin-project/go-f3/pull/608/commits/3816904e9b7c537884402becab01af98b7c49304. I'm not sure why, but the specific failing fuzz test is repeatedly clearing this cache.

**Comment by Stebalien** [comment]
Yeah, that commit makes things 2x faster...

**Comment by masih** [comment]
> Yeah, that commit makes things 2x faster...

Interesting... Also https://github.com/filecoin-project/go-f3/pull/612

**Comment by masih** [comment]
Using IPDX runners is looking hopeless, probably due to heavy demand? I might set up our own runners on K8S (with finer instance size selection). They should be cheap as they would get torn down when not in use

**Pull request closed without merging**
