### PR TITLE
Switch to uint64 for Instance and Round

### PR DESCRIPTION
**Pull request by Kubuxu**

### CODE REVIEW

**Review by Stebalien — APPROVED** [review]

**Comment by Kubuxu** [comment]
This will probably cause merge conflicts for many PRs. IDK what we want to do first.

**Comment by Kubuxu** [comment]
I will merge it as I have another branch depending on it; sorry for the conflict.

**Comment by anorth** [comment]
Why?

**Comment by Kubuxu** [comment]
1. uint32 is not supported by cbor gen
2. Although 2^32 instances probably won't happen, it is only a few orders of magnitude away.

8bytes in signature hashing won't save us, and for propagation, we will most likely use CBOR, which will encode in 4 bytes.

**Pull request merged**
