### PR TITLE
Integrate metrics for core GPBFT protocol

### PR DESCRIPTION
**Pull request by masih**
Introduce otel metrics to measure:
* number/rate of phase transitions
* histogram over the number of rounds per instance
* number of broadcasted messages
* number of re-broadcasted messages
* number of re-broadcast attempts

Part of #160

### CODE REVIEW

**Comment by Kubuxu** [comment]
Will this work with the TODO context?
Do we want to add instance number labels?

**Comment by masih** [comment]
It will work. In most cases the is no context to use and todo seems more meaningful than background. Though I have no strong opinions. 


Re labelling by instance id, my take is that we should not. That would cause explosive cardinality of metrics.

**Review by Kubuxu — APPROVED** [review]

**Comment by Kubuxu** [comment]
Can you also add metric for: instance started, instance finished?

**Comment by masih** [comment]
> Can you also add metric for: instance started, instance finished?

I had that initially but I think we can infer that using phase counter, because it is tagged by phase: increment of `INITIAL` and `TERMINATE` should indicate the instance start/termination. WDYT, does that make sense?

**Comment by Kubuxu** [comment]
That will give metrics relative to node start. I'm looking for global `instance # started` so we could see outliers.

**Comment by masih** [comment]
Sounds good; I'll add that 👍

**Comment by Kubuxu** [comment]
Yeah, I expect them to be off by one in most cases but if one node falls out of line, the state (whether it is off by one or not) tells us where things failed (failed to start or failed to terminate).

**Pull request merged**
