### PR TITLE
Order-independent fake signatures

### PR DESCRIPTION
**Pull request by Stebalien**
Make fake signatures produce the same results independent of order of the signers (assumes signatures are unique).

### CODE REVIEW

**Comment by Kubuxu** [comment]
The BLS scheme we use is order dependant, which is why the fake signature scheme replicates it.

**Comment by Stebalien** [comment]
> The BLS scheme we use is order dependant, which is why the fake signature scheme replicates it.

I see. And we expect to sort by power descending, ID ascending (same as the power table)?

**Comment by Kubuxu** [comment]
Whatever is easier. We settled on power descending because we store signers as bitfields of indexes in the power table.

**Comment by Stebalien** [comment]
Yeah, fair enough.

**Pull request closed without merging**
