### PR TITLE
Fix TestF3LateBootstrap flake

### LINKED ISSUE #684: `TestF3LateBootstrap` is flaky
Sporadically fails; [example](https://github.com/filecoin-project/go-f3/actions/runs/11144721762/job/30972633063).

### PR DESCRIPTION
**Pull request by Stebalien**
Fixes #684

### CODE REVIEW

**Comment by masih** [comment]
Fixes #684

**Comment by Stebalien** [comment]
Maybe, we'll see. I really hope this doesn't take all day again...

**Comment by Stebalien** [comment]
Ok, this has now passed twice in a row (4x test runs). So I'm going to say it's "probably" better now. I guess I didn't need to give GPBFT time to run as I thought, I just needed to advance the clock faster.

**Comment by masih** [comment]
> Well, we'll have to wait and see if it's sorted.

We can always reopen the issue if it is not. Looks much better though.

**Review by Kubuxu — APPROVED** [review]

**Pull request merged**
